### ISSUE TITLE
DSCBuild:  Allow resource modules to specify their own build scripts

### ISSUE THREAD

**Issue by dlwyatt** [PowerShellOrg/DSC#102]
Right now, we package up everything that's in source control, including Test files and any dependencies those have, into the module zip file for the pull server.  In some cases, these test dependencies may contribute a lot to the size of the zip for no reason.

We could check for something like a Deploy.ps1 script in the module's root (which would accept a path parameter for the target directory) and let each module determine which of its files are necessary in the published zip file.

Possible cons, though:  If a deployment script gets it wrong, then it could still pass tests but fail in production due to missing files.

**Comment by ArtWDrahn** [comment]
I'm happy to work on this though I don't have any immediate ideas on how to solve it.  I'll work through code and get an understanding and then mock something up.

**Comment by dlwyatt** [comment]
No worries, this is something I need for work and planned to do today anyway.  By posting the issue, I was mainly seeing if anyone piped up to say they thought we _shouldn't_ do this.  :smile:
