### ISSUE TITLE
Resolve-DscConfigurationProperty and Services vs node

### ISSUE THREAD

**Issue by BladeFireLight** [PowerShellOrg/DSC#106]
When the same value exists in both a Service that a node is part of and the node itself the service setting is being returned when calling Resolve-DscConfigurationProperty. but when a setting is in AllNodes or a Node the value in AllNodes is returned.

Would it not make sense for the most spacific (IE the Node) value be returned?

**Comment by dlwyatt** [comment]
That's still a point of confusion for me.  Essentially, you can think of it as two parallel trees:

Service (Global) -> Service (Site) -> Service (Node)
Global -> Site -> Node

If a service value exists, then the most specific Service override takes effect, and the second set isn't even checked.  If there aren't any values in the service scopes, then the normal node stuff would kick in.  Here's how you do service overrides at the site / node level:

```posh
# In a node or site file:
@{
    Services = @{
        ServiceName = @{
            SettingName = 'Some Value'
        }
    }
}

# In the service file:

@{
    SettingName = 'Some Value'
}
```

**Comment by dlwyatt** [comment]
At one point, I did a complete rewrite of the Resolve-DscConfigurationProperty code that simplified this stuff, but Steven convinced me to put some of the original logic back.  There are use cases for these service-specific overrides.

**Comment by BladeFireLight** [comment]
Thanks, actually makes sense, but It was not what I was expecting and it almost killed a handful of branch servers that got the wrong setting :(

**Comment by smurawski** [comment]
Yeah, if you need to override a service setting by node, the node needs the service defined.

The structure is optimized for making changes at the highest level possible with the flexibility to override on demand.  

With the order checked being:
Node/Service -> Site/Service -> Service -> Node -> Site -> Global
