### ISSUE TITLE
Get-DscConfigurationData filtering behavior

### ISSUE THREAD

**Issue by BladeFireLight** [PowerShellOrg/DSC#109]
I'm not sure if this was the intended behavior. but when filtering for a single name or nodename none of the site, service or credentials are loaded. 

with out that data the returned configuration data is not a complete set that a single node would use. 

Is there a reason behind this?

**Comment by usepowershell** [comment]
The reason was I only used that filter to get back node information.  I had no reason to load the additional information. 

Changed on the development branch via https://github.com/PowerShellOrg/DSC/commit/cc6a256526555a190052739066db84780176eb4e
