### ISSUE TITLE
DSC Resource 

### ISSUE THREAD

**Issue by SuperMarioo** [PowerShellOrg/DSC#111]
Hi,

I would like to share my  DSC Resource cFolderQuota .
Are you going to create the folder for me ?
I'm not sure how to upload it here 

Regards 

Mariusz

**Comment by dlwyatt** [comment]
Is this something you've added to an existing module, or a new module?  If it's a new module, we'll set up a new repository to host it here, and give you permission to commit code.

**Comment by SuperMarioo** [comment]
That's a new module .

**Comment by dlwyatt** [comment]
OK.  What's the module's name?

**Comment by SuperMarioo** [comment]
cFolderQuota  which contains DSC Resources cFolderQuota  and cQuotaTemplate

**Comment by dlwyatt** [comment]
I've created the repository https://github.com/PowerShellOrg/cFolderQuota , and sent you an invite to join the PowerShellOrg organization on GitHub.  You should be receiving an email about that any time now.

You should be all set to clone the new repo and push updates to it.  Please let me know if you have any trouble.
