### ISSUE TITLE
cSmbshare Test-TargetResource FIX 

### ISSUE THREAD

**Issue by SuperMarioo** [PowerShellOrg/DSC#112]
Hi , 

I have fixed Test -TargetResource in cSmbShare Resource .

Can I upload  it here ?

Regards 

Mariusz

**Comment by dlwyatt** [comment]
Yep!  Just fork https://github.com/PowerShellOrg/cSmbShare , and then submit a pull request with your changes.

(If you're not familiar with this process yet, refer to https://help.github.com/articles/using-pull-requests/ )
