### ISSUE TITLE
Documentation for DSC tooling

### ISSUE THREAD

**Issue by cstewart87** [PowerShellOrg/DSC#116]
Is there an external wiki or docs that explain how to use these tooling modules?

**Comment by BladeFireLight** [comment]
If your talking about the development branch, the example is missing a few settings.  I'm actually working on a blog series (bladefirelight.wordpress.com) about setting it up in my home lab. Tomorrow I will post  about the changes to get the example to build. 

I actually have it working in production at work but that evolved along with the tools over the last 12 months, and I am not allowed to write about the inner workings of my employer.

**Comment by BladeFireLight** [comment]
I also plan to submit a pull request to update the readme with full instructions when I'm done.

**Comment by BladeFireLight** [comment]
https://bladefirelight.wordpress.com/2015/05/03/invoke-dscbuild-test-lab-2/

As promised. some documentation to get it working.

**Comment by cstewart87** [comment]
I had not seen the development branch documentation, thanks for pointing it out!  Also, thanks for sharing your blog post.  I'll be sure to look through that as well.
