### ISSUE TITLE
New Resources for ElasticSearch, NSSM, 7zip and JRE

### ISSUE THREAD

**Issue by lawrencegripper** [PowerShellOrg/DSC#118]
Hi, 

I've got a new set of resources for setting up Elastic Search and Kibana. Most of the resources written to get this done are also fairly broad, like NSSM, JRE and 7Zip so wondering if repo for general GripDevResources would be a good name?

**Comment by tysonjhayes** [comment]
First that'd be awesome if you published those I was looking to play with Elastic Search and Kibana soon and that'll help stand up stuff quciker.

Secondly I'm not sure GripDevResources is a great name. What does Grip have to do with these resources? Though I'm coming up on a blank for better names.

**Comment by lawrencegripper** [comment]
Cool, yeah resources will setup a windows box with Kibana and Elasticsearch services in default config nice a quickly. Depending usage was going to look at cluster setup further down the line, very much just evaluating at the moment. 

Agreed, logic goes that I blog as gripdev so followed the naming convention of other resources that are a mixed bag of stuff, like the stackoverflowresources repo. 

Happy to go with whatever fits best really!

**Comment by ducke** [comment]
:+1: for ELK DSC Resources

**Comment by tysonjhayes** [comment]
I am of the opinion that the resources should be named after a grouping of what they do and not necessarily after the author. It'll help the duplication of resources where people are unware that the DSC Resource they want exists if they go into a custom name (such as StackExchange). Even the PS team has done this with xService in the xPSDesiredStateConfiguration module. Which personally I find confusing to try to rememer to find.

**Comment by lawrencegripper** [comment]
It's a tough call as collectively the resources allow the install of Elasticsearch and Kibana but I plan to reuse the JRE stuff, cNSSM and c7zip modules to create a DSC for SonarQube. 

In that scenario I'd have a cElastic and cSonarQube repo with duplicated resources which doesn't feel nice.

**Comment by tysonjhayes** [comment]
While it may not ideal you could create c7zip and cNSSM as their own DSC resources and reference them in cElastic and cSonarQube as [composite resources](http://blogs.msdn.com/b/powershell/archive/2014/02/25/reusing-existing-configuration-scripts-in-powershell-desired-state-configuration.aspx) allowing the c7zip and cNSSM to be their own resources and projects for people to reference in their own resources.

**Comment by lawrencegripper** [comment]
Sounds like a good plan, shall we go for cElastic then?

**Comment by tysonjhayes** [comment]
Sounds good to me. I'll gladly give you feedback and run some tests if you want. Just let me know!

**Comment by lawrencegripper** [comment]
Thanks, it's fairly rough and ready so could do with some feedback and contributions. 

@smurawski or @dlwyatt can you create a repo for the resources in the org?

**Comment by usepowershell** [comment]
I've created a repo, but let's stop with the 'c' stuff.

**Comment by lawrencegripper** [comment]
@smurawski Thanks for setting up the repo, tried to push but doesn't look the GripDevResources Team has access to it. 

![image](https://cloud.githubusercontent.com/assets/1939288/8083074/f69aa54a-0f79-11e5-827b-da4d9f92c511.png)

**Comment by usepowershell** [comment]
Sorry, will check that in a few.

**Comment by usepowershell** [comment]
@lawrencegripper Should be fixed now.

**Comment by lawrencegripper** [comment]
Thanks, all sorted [resources pushed now](https://github.com/PowerShellOrg/GripDevResources)

What's the move away from the c prefix about, happy to refactor? Was following the convention around c for Community and x for Experimental from MS blog post I read a while back.

**Comment by usepowershell** [comment]
'c' was for resources forked from microsoft's 'x' resources.  Now those resources are finally on Github and we can start the process of pushing our changes upstream and hopefully deprecating any 'c' resources.
