### ISSUE TITLE
cAppPool Test-TargetResource incorrectly reports password not matching

### ISSUE THREAD

**Issue by jpflum** [PowerShellOrg/DSC#24]
The line of code where the password value is tested currently uses the "-eq" operator and should be using the "-cne" operator (password are case sensitive which is why I added the "c". The code is:
<<<
               $clearTextPassword = $Password.GetNetworkCredential().Password
                if($clearTextPassword -eq $PoolConfig.add.processModel.password){
                    $UpdateNotRequired = $false
                    & $env:SystemRoot\system32\inetsrv\appcmd.exe set apppool $Name /processModel.password:$clearTextPassword
                }
 >> 
... and should be...
<<<
               $clearTextPassword = $Password.GetNetworkCredential().Password
                if($clearTextPassword -cne $PoolConfig.add.processModel.password){
                    $UpdateNotRequired = $false
                    & $env:SystemRoot\system32\inetsrv\appcmd.exe set apppool $Name /processModel.password:$clearTextPassword
                }
 >>

**Comment by usepowershell** [comment]
Closed by https://github.com/PowerShellOrg/cWebAdministration/commit/1d1a522b0a1a8ca3c089e6800a94c9f9b9ff7164
