### ISSUE TITLE
cAppPool resource not executing

### ISSUE THREAD

**Issue by jimmarch** [PowerShellOrg/DSC#25]
Just a simple config
configuration MyApp
{
    Import-DscResource -modulename cWebAdministration
    node localhost
    {
        cAppPool NewPool
        {
            Name = 'TestAppPool'
            Ensure = 'Present'
        }
    }
}
MyApp

Results in this error...

PS C:\Users\a_jmarch> Start-DscConfiguration -Path .\MyWeb -wait -Verbose
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' =
 MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer JMARCH02 with user sid S-1-5-21-3595392803-2728658066-1154433773-43208.
VERBOSE: [JMARCH02]: LCM:  [ Start  Set      ]
VERBOSE: [JMARCH02]: LCM:  [ End    Set      ]
Failed to get exported command Get-TargetResource from module PSHOrg_cAppPool. Please check the module definition. 
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : GetTargetResourceCommandNotFound
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.119 seconds

**Comment by keyrage** [comment]
Just to confirm this is still happening with the cAppPool resource. Steven's quick fix of deleting the PSD1 seems to work. 

Interestingly I looked at some of the experimental DSC resources from Microsoft and they don't include a PSD1 for each resource. There is a PSD1 for the parent module but each resource is purely a PSM1 and MOF schema file. There's a bit of inconsistency about whether they use an "Export-Moduolemember" to export the functions within the psm1.

I'd be inclined to suggest that the community DSC resources follow a similar pattern of only using the PSD1 at the base module and not include one for each DSC resource?

**Comment by dlwyatt** [comment]
Fixed on https://github.com/PowerShellOrg/cWebAdministration .  The module manifest was missing its RootModule key, causing the PSM1 file not to load properly.  (Deleting the optional psd1 file was also an option, but I decided to leave it since it contained author credits and such.)

**Comment by smurawski** [comment]
And I'm in favor of keeping the PSD1.  There are still a few edge cases I've hit where resources would not load without one.

**Comment by matthewhatch** [comment]
That's interesting... I actually removed the psd1 from my fork, but will add it back.
