### ISSUE TITLE
Publish these resources to the PSGallery

### ISSUE THREAD

**Issue by rkeithhill** [PowerShellOrg/DSC#41]
It would be way more convenient to install these resources if you published them to the PSGallery so I could install them all with:

Install-Module cPSHOrgResources

I'm thinking that you could put all of the resources into a single module - or not.  I'm OK as long as I can get cPSGet easily even if it is with:

Install-Module cPSGet

:-)

**Comment by usepowershell** [comment]
We've got some resources out on the gallery now and there are several efforts to try to get a more consistent deployment going.
