### ISSUE TITLE
Invoke-DscBuild throws error if cNetworking is in DSC_Resources

### ISSUE THREAD

**Issue by BladeFireLight** [PowerShellOrg/DSC#67]
Invoke-DscBuild ends with this error. 

WARNING: Get-TargetResource should return a [Hashtable] mapping all schema properties to their values. Prepend the
param block with [OutputType([Hashtable])].
WARNING: Test-TargetResource should return a [boolean]. Prepend the param block with [OutputType([Boolean])].
WARNING: Get-TargetResource should return a [Hashtable] mapping all schema properties to their values. Prepend the
param block with [OutputType([Hashtable])].
WARNING: Test-TargetResource should return a [boolean]. Prepend the param block with [OutputType([Boolean])].
New-cDscResourceProperty : ValidateSet can not be used for Arrays, PSCredentials, and Hashtable.
At C:\Program Files\WindowsPowerShell\Modules\cDscResourceDesigner\cDscResourceDesigner.psm1:3211 char:24
+         $properties += New-cDscResourceProperty `
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : InvalidValidateSetUsageError,New-cDscResourceProperty

**Comment by dlwyatt** [comment]
Fixed in the latest versions of cNetworking and cDscResourceDesigner.
