### ISSUE TITLE
Test-NodeRoll

### ISSUE THREAD

**Issue by BladeFireLight** [PowerShellOrg/DSC#69]
in http://powershell.org/wp/2014/05/22/building-scalable-configurations-with-dsc/
Steve's example configs have a Test-NodeRoll function.  Do we have plans to add that function to GitHub?

**Comment by usepowershell** [comment]
@BladeFireLight if you still want this - you've got commit rights now.. Otherwise, feel free to close it.

**Comment by BladeFireLight** [comment]
Now that I have an understanding of the code It makes little sense to use Rolls at all. I can set the Service in the node or use wild cards in the Service. and then use a more generic build script. 

Sent from Windows Mail

From: Steven Murawski
Sent: ‎Friday‎, ‎July‎ ‎10‎, ‎2015 ‎10‎:‎09‎ ‎AM
To: PowerShellOrg/DSC
Cc: BladeFireLight

@BladeFireLight if you still want this - you've got commit rights now.. Otherwise, feel free to close it.
